### ISSUE TITLE
Lab Report 4 Feedback

### ISSUE THREAD

**Issue by syptic** [jdweak/cse15l-lab-reports#4]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
- [ ] Provides link to the markdown-parse repository they reviewed

Snippet 1

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [ ] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 2

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [ ] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 3

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [ ] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Additional comments from your grader:
You did it for Prof. Joe's repo instead of the one reviewed in your lab. Go ahead and change the other testing repo and submit a regrade request after that.

Feel free to comment below any questions about the rubric/feedback

**Comment by jdweak** [comment]
I've updated my report to reflect the repository we went over in lab instead of Joe's. Also, since the lab report is still ungraded in gradescope I am unable to submit a regrade request. Let me know what I should do from here, thanks!

Github Report Page: [](url)(https://jdweak.github.io/cse15l-lab-reports/lab-report-4-week-8.html)

**Comment by jdweak** [comment]
Now that Gradescope has scores inputted for the report I have submitted a regrade request.
